name: ayadati
description: "Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.3.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dots_indicator: ^4.0.1
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_facebook_auth: ^7.1.6
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  get_it: ^9.2.1
  google_fonts: ^8.1.0
  google_sign_in: ^6.2.1
  intl: ^0.20.2
  modal_progress_hud_nsn: ^0.5.1
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: app_images.dart

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_app.png"
  min_sdk_android: 21
flutter_intl:
  enabled: true
